name: UX Fika
favicon: null
layout_spectrum: 0.2398890641052276
typography_spectrum: 0.43917351635172963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8961832907516509
  lightness: 0.004949166439473629
  saturation: 0.588813801528886
  rhythmicContrast: 0.25620491500012577
purpose: []
